modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/buriedwrecks/issues"
license="MIT"

[[mods]]
modId="buriedwrecks"
version="${file.jarVersion}"
displayName="Buried Wrecks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/buriedwrecks"
authors="Mrbysco"
description='''
What sort of music did cave men listen to? Hard Rock!
'''
[[dependencies.buriedwrecks]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.buriedwrecks]]
modId="neoforge"
type="REQUIRED"
versionRange="[21.0.31-beta,)"
ordering="NONE"
side="BOTH"